### ISSUE TITLE
Introduce galvan integration tests in tc platform

### ISSUE THREAD

**Issue by anthonydahanne** [Terracotta-OSS/terracotta-platform#146]
Using passthrough based tests is not enough anymore : we've been bitten several times by integration issues (META-INF/services typos) that can only be tested starting a "real" tc server.

Galvan should provide us with the necessary infrastructure to start / stop  tc server

This issue should be closed when galvan based integration test(s) is(are) added to tc platform

**Comment by mathieucarbou** [comment]
will be done as required, for #154 #162 #171
