### ISSUE TITLE
[mnm] Failover support on client-side

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/terracotta-platform#154]
When a failover happens, the client-side entity should makes the management layer aware there has been a reconnection so that the management layer can re-expose the management metadata of the client.

As discussed with @jd0-sag : supposed to be working by using `EndpointDelegate.createExtendedReconnectData`, to pass the reconnect information to the new server entity (that will include the management metadata).

For this to work, we would need that this ordering applies:
1. without any ordering:
   A: `EndpointDelegate.createExtendedReconnectData()`called on client-side
   B:  platform informs the monitoring service about the platform changes (new server states, client leaves, joins, etc)
2. `ActiveServerEntity.handleReconnect()` called on server-side
3. The server entity can expose the incoming management metadata in the byte array[] in the monitoring service, for the associated client descriptor because the client exists in the topology thanks to 1. B.

@anthonydahanne new notification: `CLIENT_RECONNECTED`

**Comment by mathieucarbou** [comment]
@anthonydahanne : FYI.

@jd0-sag : could you please confirm that this would work ? Thanks :-)

**Comment by jd0-sag** [comment]
> so that the management layer can re-expose the management metadata of the client

What does this mean?  The call to `EndpointDelegate.createExtendedReconnectData()` should just return a description of whatever that meta-data is, which the client knows and the server doesn't.

Otherwise, what you have described sounds correct, if I am correctly understanding it.

**Comment by mathieucarbou** [comment]
@jd0-sag : exposing management metadata means: the client invokes the management entity with its serializable management metadata as parameter, and the management entity put this data in the tree behind, under the client "client descriptor".

**Comment by jd0-sag** [comment]
Ok, so it sounds like it is just some information normally sent as an invoke which describes something about the state of this client.

Serializing whatever the current state of that is as the extended reconnect data is the right way to handle this case (it is specifically made to allow the server to reconstruct any client state it needs to know about) so this should work well.

**Comment by mathieucarbou** [comment]
ok! thanks!
