### ISSUE TITLE
lease-service.xsd : lease-length can be confusing

### ISSUE THREAD

**Issue by lorban** [Terracotta-OSS/terracotta-platform#336]
Currently, the lease configuration works like this:

```
<lease:lease-length>5000</lease:lease-length>
```

which isn't incorrect as the XSD documents the value is in milliseconds but it's nevertheless confusing. This should be refactored such as the config would look like this:

```
<lease:lease-duration unit="seconds">30</lease:lease-duration>
```

Eventually, the `unit` could have a default, which IMHO should be minutes or seconds.

**Comment by ChrisGreenaway** [comment]
Fixed by https://github.com/Terracotta-OSS/terracotta-platform/pull/338
