### ISSUE TITLE
Using the `javax.xml.bind` utility classes for data type conversion causes unnecessary dependencies on JAXB.

### ISSUE THREAD

**Issue by chrisdennis** [Terracotta-OSS/terracotta-platform#544]
A couple of management classes are using `DataTypeConverter` methods to do simple Base64/Hex encoding/decoding. This is causing the management code to depend on JAXB which causes issues when running in Java 11+ (especially within an OSGi environment).

**Comment by mathieucarbou** [comment]
well... this is not really a bug ;-)
much more a change required to be able to run with 11+ and osgi, so much more a feature then ;-)

**Comment by chrisdennis** [comment]
It's a change to be able to run with 11+ full stop.

**Comment by anthonydahanne** [comment]
is there a PR out already ?

**Comment by anthonydahanne** [comment]
ah, found it; it's #545  and it was merged; closing then
