### ISSUE TITLE
Use static determination of MAC address in org.terracotta.management.sequence.Defaults

### ISSUE THREAD

**Issue by cljohnso** [Terracotta-OSS/terracotta-platform#568]
Calculating an interface's MAC address on a Windows machine is noticeably slow.  `org.terracotta.management.sequence.Defaults#readMacAddress`  is currently set up to do a MAC address calculation for every call.  For situations in which repeated calls are made, particularly in testing, the amount of time spent in MAC address calculation is significant even though, within a single JVM, the MAC address really should not change.  The calculation should be changed so that, once performed, it is not repeated -- each subsequent call to `readMacAddress` would return the previously calculated value.

**Comment by mathieucarbou** [comment]
to speed up tests and completely avoid reading the mac, we could also provide another node id generator that could take the node id from a system property, or a version where the mac would be provided through a system property. At the end, the goal is to be able to have a unique id for the sequence generator.
