### ISSUE TITLE
Run tests with a Java 11 JVM path (or another one) taken from toolchains.xml

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/terracotta-platform#636]
- For Lin and Win
- Remove temporary profiles put in the pom with hard-coded paths to JVM 11

CC @saurabhagas

**Comment by mathieucarbou** [comment]
will try to use the forge plugin

**Comment by akomakom** [comment]
> will try to use the forge plugin

I'll make a PR after https://github.com/Terracotta-OSS/terracotta-parent/pull/11

**Comment by mathieucarbou** [comment]
Closing since this is resolved by PR https://github.com/Terracotta-OSS/terracotta-platform/pull/663 in commit 791a3d4cdc5e86117d47e1b0876e1dc2b2f6e709.

Solution implemented by using the GMvane plugin to read the toolchains.xml file to extract the JVM path for the requested JVM version, which will be used for the tests,
Solution works for any java version on the toolchain file: 1.8, 1.9, 1.11, etc.
Solution also keeps the same plugin versions as we had in tc-platform before.

Consequently, the issue can be solved at the moment without involving any parent pom, plugin version changes and forge integration.

If someone sees a missing use case or an issue not resolved, or a valid use case requiring the use of one of these things above, feel free to open another issue describing the problem / use case to solve. 
The current issue (ability to run the tests by looking up the JVM path in the toolchains) is solved at the moment by using a simple plugin.

In any case, if there is a change of implementation, __here are the requirements and things to verify for this project__ to have parity with master:

### Fast build

This project is big and development and testing time is highly impacted by Maven build time since there is no gradle cache.
So we need to be able several times per day to build the project __fast__.

`./mvnw clean install -DskipTests -Dfast`

The command should only do the minimal required steps:

- compilation steps
- felix
- packaging (jars and source jars - to use snapshots in downstream projects)

__No toolchain, verfication, license check, findbugs, etc.__

The command needs to be fast: __less than 30 seconds.__

### Unit tests vs IT tests

We should be able to run the unit tests only and all tests:

- `./mvnw clean verify -DskipTests -Dfast` => should skip all tests
- `./mvnw clean verify -DskipITs -Dfast` => should skip IT Galvan and Angela tests but run unit tests (__last ~2-3min__)
- `./mvnw clean verify` => should run everything, like on Azure. __Lasts ~1h20min__

### Plugin config

- Use `<trimStackTrace>false</trimStackTrace>`
- Use `<argLine>--illegal-access=permit</argLine>` (only for Java 11, because core is doing some illegal reflection calls)

### Test JVM

We should be able to run the tests with one of the JVM on the toolchain but compilation done in 1.8

__Examples__

Run a test with Java 11 (will look at your toolchains.xml file to fine the JVM):

```
./mvnw verify -f management/testing/integration-tests/pom.xml -Dit.test=DiagnosticIT -Djava.test.version=1.11
```

Run a test with Java 8 (will look at your toolchains.xml file to fine the JVM):

```
./mvnw verify -f management/testing/integration-tests/pom.xml -Dit.test=DiagnosticIT -Djava.test.version=1.8
```

Run a test with Java 8 (will look at your toolchains.xml file to fine the JVM - 1.8 is teh default):

```
./mvnw verify -f management/testing/integration-tests/pom.xml -Dit.test=DiagnosticIT
```

Run a test by using the default JAVA_HOME found from your shell. -Dfast has no enforcement at all and does not use toolchain. 
-Dfast goal is to compile and package fast.

```
./mvnw verify -f management/testing/integration-tests/pom.xml -Dit.test=DiagnosticIT -Dfast
```

__The same applies for Angela tests in dynamic-config/testing/system-tests and they should be verified as well__

__Verification__

Look inside the servers logs of the nodes starte by Angela and Galvan.
The server logs contain the list of system properties and JVM details used to start the servers.
The version should match the one requested.

- For Angela tests: `target/angela/work/XYZ/logs/stripe1/node-1-1/terracotta.server.log`
- For Galvan tests: `target/galvan/XYZ/stripe1/testServer0/logs/terracotta.server.log`

Look for something like that in the logs:

```
java.runtime.name             : OpenJDK Runtime Environment
java.runtime.version          : 11.0.6+10
java.specification.name       : Java Platform API Specification
java.specification.vendor     : Oracle Corporation
java.specification.version    : 11
```

### IDE support

After having done a `./mvnw clean verify -DskipTests -Dfast` to build the project and kit, you should be able to go in your IDE and right-click run the tests for example.

This must be verified both both Angela tests and management tests, by trying ot run the `DiagnosticIT` test. 
This tests is in both modules.
