### ISSUE TITLE
config-tool command output is not scripting friendly

### ISSUE THREAD

**Issue by chrisdennis** [Terracotta-OSS/terracotta-platform#718]
We should make sure to separate 'data' from 'errors and/or diagnostics' in the output of the `config-tool`. This is particularly important if someone tries to use the output of a `get` or `export` command piped directly to another command.

**Comment by mathieucarbou** [comment]
Currently:

1. All the outputs goes through logback, which goes to system.out currently.
2. log.info logs are those seen by user
3. get / export command can output some log.info logs prior to the "data" output
4. errors, warns or exceptions are not redirected to system/err

Proposal:

1. Have a better logback that is sending all what is > INFO to system.err
2. Remove the log.info logs for the get / export command

I think this would cover all the use cases and would apply this global behavior also to other commands.

**Comment by mathieucarbou** [comment]
@chrisdennis @saurabhagas : what is the status for this now ?

**Comment by mathieucarbou** [comment]
fixed but probably need to verify the code to ensure the right API is there to not make a mistake and put something unwanted in stdout
