### ISSUE TITLE
Non serialisable ConcurrentHashMap.MapEntry

### ISSUE THREAD

**Issue by ljacomet** [Terracotta-OSS/terracotta-platform#79]
The `entrySet()` operation had a serialisation related bug on the server side - in Java 8, the default `ConcurrentHashMap$MapEntry` is not `Serialazable` and thus the entries need to be wrapped instead in an `AbstractMap$SimpleEntry`.

**Comment by ramsai1729** [comment]
This is not a bug as the code is using a wrapper class com.terracotta.entity.map.common.MapEntry (which is serializable) not ConcurrentHashMap$MapEntry

**Comment by ljacomet** [comment]
@ramsai1729 If you look at the code I committed for this in the PR #80 you will see that there were inconsistencies in my implementation. Btw I got rid of MapEntry and instead used `AbstractMap#SimpleEntry`.
