### ISSUE TITLE
start-tc-server.sh is not a Bourne Shell (plain sh) script

### ISSUE THREAD

**Issue by lorban** [Terracotta-OSS/terracotta-platform#86]
The server's start script declares `#!/bin/sh` as its first line, but when executed with plain `sh` (and not bash) the script enters an infinite loop that prints the following line:

```
./server/bin/start-tc-server.sh[119]: /dev/null: bad file unit number
```

Either the script should be adapted to work with the real `/bin/sh` shell or should be declared as a `bash` script.

**Comment by jd0-sag** [comment]
A PR was posted, yesterday, to address this:  https://github.com/Terracotta-OSS/terracotta-core/pull/220

It will merge today after a few other items.
